In [60]:
import numpy as np

In [61]:
## Creating an array of 10 zeros
ZeroArray = np.zeros((10))
ZeroArray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
## Creating an array of 10 ones 
OnesArray = np.ones(10)
OnesArray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
## Creating an array of 10 fives by multiplying the previous array of ones by the number five
FiveArrays = OnesArray*5
FiveArrays

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [64]:
## Creating an array of random integers between the numbers of ten and fifty 
TenFiftyInteger = np.random.randint(10,50,10)
TenFiftyInteger

array([22, 15, 38, 18, 15, 23, 27, 19, 22, 12])

In [65]:
## Used a function to arrange the integers between ten and fifty in an even fashion, skipping every odd number
EvenIntArray = np.arange(10,51,2) 
EvenIntArray

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [66]:
## Creating a 3x3 matrix via a reshaping function used on a standard array from 0 to 8
tree = np.arange(9)
tree
tree.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
## Pulling a random number (including decimals) between zero and one
np.random.rand(1)

array([0.34246948])

In [68]:
## Creating an array  from one to 25 to be used in the next problem
matog = np.arange(1,26).reshape(5,5)
matog

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [69]:
## New matrix from one to 25 without the reshaping
mat = np.arange(1,26)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [70]:
## Summing all the values of the previous array 
mat.sum()

325

In [71]:
## Getting the standard deviation of the previous array
mat.std()

7.211102550927978

In [72]:
## Creating a new array of twenty-five ones
mat1 = np.ones(25)
mat1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
## Creating a new array summing the values of the previous two arrays
mat1 + mat

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.])

In [74]:
## Creating a new array multiplying the values of the previous two arrays 
mat1 * mat

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])